### ISSUE TITLE
Multichain support

### ISSUE THREAD

**Issue by arbazkiraak** [kesar/deth-extension#1]
https://twitter.com/dethcrypto/status/1473001241970159621

**Comment by kesar** [comment]
good idea, what are all the etherscan domains we should cover?

https://arbiscan.io
https://polygonscan.com
https://bscscan.com
https://optimistic.etherscan.io

anything else?

**Comment by arbazkiraak** [comment]
testnet.snowtrace.io
testnet.bscscan.com
polygonscan.com
hecoinfo.com
explorer-mainnet.maticvigil.co
explorer.fuse.io
arbiscan.io

for both mainnet and testnet.

**Comment by arbazkiraak** [comment]
Also, Please push the update for the chrome store extension.

**Comment by arbazkiraak** [comment]
https://github.com/kesar/deth-extension/pull/2

**Comment by kesar** [comment]
app submited for review 👍🏻
